// Code generated by "stringer -type=vmStatus"; DO NOT EDIT.

package vminstance

import "strconv"

const _vmStatus_name = "NewStatusRunningStatusFinishedStatusErrorStatus"

var _vmStatus_index = [...]uint8{0, 9, 22, 36, 47}

func (i vmStatus) String() string {
	if i >= vmStatus(len(_vmStatus_index)-1) {
		return "vmStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _vmStatus_name[_vmStatus_index[i]:_vmStatus_index[i+1]]
}
